In [2]:
def sum_numbers(*args):
    result=0
    for num in args:
        result+=num
    print("sum = ",result)
print("similer method overloading concept")
print("single argument : ",end="")
sum_numbers(10)
print("double argument : ",end="")
sum_numbers(10,2)
print("multiple argument : ",end="")
sum_numbers(1,2,3,4)

similer method overloading concept
single argument : sum =  10
double argument : sum =  12
multiple argument : sum =  10


In [3]:
def fun(a):
    print("x")
def fun(a,b):
    print("y")
fun(9)

TypeError: fun() missing 1 required positional argument: 'b'

In [9]:
 class A:
        def first(self):
            print("1st function of class A")
        def second(self):
            print("2nd function of class A")
class B(A):
    def first(self):
        print("1st function of class A in class B")
    def display(self):
        print("end function of class A in class B")
obj=B()
obj.first()
obj.second()

1st function of class A in class B
2nd function of class A


In [14]:
class A:
    def __init__(self,a):
        self.a=a
    def __add__(self,other):
        return self.a+other.a
obj1=A(1)
obj2=A(2)
obj3=A("Hello")
obj4=A("hii")
print(obj1+obj2)
print(obj3+obj4)

3
Hellohii


In [15]:
class A:
    def __init__(self,a):
        self.a=a
    def __gt__(self,other):
        if self.a>other.a:
            return True
        else:
            return False
obj1=A(5)
obj2=A(9)
if obj1>obj2:
    print("obj1 is greater")
else:
    print("obj2 is greater")

obj2 is greater


+ -> __add__(self,other)
- -> __sub__(self,other)
* -> __mul__(self,other)
/ -> __truediv__(self,other)
// -> __floordiv__(self,other)
% -> __mod__(self,other)
** -> __pow__(self,other)
< -> __lt__(self,other)
> -> __gt__(self,other)
<= -> __le__(self,other
>= -> __ge__(self,other
== -> __eq__(self,other
!= -> __ne__(self,other)

In [29]:
class A:
    def __init__(self,a):
        self.a=a
    def __mul__(self,other):
        c=self.a%other.a
obj1=A(2)
obj2=A(3)

In [30]:
class parent:
    def func1(self):
        print("hello parent")
class child(parent):
    def func2(self):
        print("hello child")
obj=child()
obj.func1()
obj.func2()

hello parent
hello child


In [34]:
class parent1:
    def func1(self):
        print("hello parent1")
class parent2:
    def func2(self):
        print("hello parent2")
class parent3:
    def func2(self):
        print("hello parent3")
class child(parent1,parent2,parent3):
    def func3(self):
        print("hello child")
obj=child()
obj.func1()
obj.func2()
obj.func3()
print(child.__mro__)

hello parent1
hello parent2
hello child
(<class '__main__.child'>, <class '__main__.parent1'>, <class '__main__.parent2'>, <class '__main__.parent3'>, <class 'object'>)


In [ ]:
-------------------------------------------------------------------------------------------------------------------------------

In [4]:
class parent:
    def fun1(self):
        print("hello parent")
class child1(parent):
    def fun2(self):
        print("hello child1")
class child2(parent):
    def fun3(self):
        print("hello child2")
obj1=child1()
obj2=child2()
obj1.fun1()
obj1.fun2()
obj2.fun1()
obj2.fun3()

hello parent
hello child1
hello parent
hello child2


In [6]:
class parent1:
    def fun1(self):
        print("parent 1")
class parent2:
    def fun2(self):
        print("parent 2")
class child1(parent1):
    def fun3(self):
        print("child 1")
class child2(child1,parent2):
    def fun4(self):
        print("child 2")
obj1=child1()
obj2=child2()
obj1.fun1()
obj1.fun3()
obj2.fun1()
obj2.fun2()
obj2.fun3()
obj2.fun4()

parent 1
child 1
parent 1
parent 2
child 1
child 2


In [7]:
class parent:
    def __init__(self):
        self.attr1=50
        self.attr2=60
class child(parent):
    def __init__(self):
        self.attr3=45
obj=child()
print(obj.attr1)

AttributeError: 'child' object has no attribute 'attr1'

In [8]:
class parent:
    def __init__(self):
        self.attr1=50
        self.attr2=60
class child(parent):
    def __init__(self):
        super().__init__()
        self.attr3=45
obj=child()
print(obj.attr1)
#parent__init__(self)

50


In [9]:
class parent:
    def display(self):
        print("hello parent")
class child(parent):
    def display(self):
        print("hello child")
obj=child()
obj.display()
obj.display()

hello child
hello child


In [10]:
class parent:
    def func1(self):
        print("hello parent")
class child(parent):
    def fun2(self):
        print("hello child")
print(issubclass(child,parent))
print(issubclass(parent,child))

True
False


In [11]:
class parent:
    def func1(self):
        print("hello parent")
class child(parent):
    def fun2(self):
        print("hello child")
A=child()
B=parent()
print(isinstance(A,child))
print(isinstance(A,parent))
print(isinstance(B,child))
print(isinstance(B,parent))

True
True
False
True


In [12]:
class A:
    def rk(self):
        print("class A")
class B(A):
    def rk(self):
        print("class B")
class C(A):
    def rk(self):
        print("class C")
class D(B,C):
    pass
obj=D()
obj.rk()
print(D.mro())

class B
[<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>]


In [15]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("foo from p2")
class c1(p1):
    pass
class c2(p2):
    def bar(self):
        print("bar form c2")
class GCC(c1,c2):
    pass
obj=GCC()
obj.foo()
obj.bar()
print(GCC.mro())

foo from p1
bar form c2
[<class '__main__.GCC'>, <class '__main__.c1'>, <class '__main__.p1'>, <class '__main__.c2'>, <class '__main__.p2'>, <class 'object'>]


In [16]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("foo from p2")
class c1(p1):
    pass
class c2(p1):
    def bar(self):
        print("bar form c2")
class GCC(c1,c2):
    pass
obj=GCC()
obj.foo()
obj.bar()
print(GCC.mro())

foo from p1
bar form c2
[<class '__main__.GCC'>, <class '__main__.c1'>, <class '__main__.c2'>, <class '__main__.p1'>, <class 'object'>]


In [17]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("foo from p2")
class c1(p1,p2):
    pass
class c2(p1,p2):
    def bar(self):
        print("bar form c2")
class GCC(c1,c2):
    pass
obj=GCC()
obj.foo()
obj.bar()
print(GCC.mro())

foo from p1
bar form c2
[<class '__main__.GCC'>, <class '__main__.c1'>, <class '__main__.c2'>, <class '__main__.p1'>, <class '__main__.p2'>, <class 'object'>]


In [18]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("foo from p2")
class c1(p1,p2):
    pass
class c2(p1):
    def bar(self):
        print("bar form c2")
class GCC(c1,c2):
    pass
obj=GCC()
obj.foo()
obj.bar()
print(GCC.mro())

foo from p1
bar form c2
[<class '__main__.GCC'>, <class '__main__.c1'>, <class '__main__.c2'>, <class '__main__.p1'>, <class '__main__.p2'>, <class 'object'>]


In [19]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("foo from p2")
class c1(p1,p2):
    pass
class c2(p2):
    def bar(self):
        print("bar form c2")
class GCC(c1,c2):
    pass
obj=GCC()
obj.foo()
obj.bar()
print(GCC.mro())

foo from p1
bar form c2
[<class '__main__.GCC'>, <class '__main__.c1'>, <class '__main__.p1'>, <class '__main__.c2'>, <class '__main__.p2'>, <class 'object'>]


In [30]:
from abc import ABC,abstractmethod
class shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
    @abstractmethod
    def draw(self):
        pass
class circle(shape):
    def __init__(self):
        super().__init__("cicrle")
    def draw(self):
        print("drawing :",self.shape_name)
obj=circle()
obj.draw()

drawing : cicrle


In [37]:
class book:
    def __init__(self,name,n,authors,publisher,ISBN,year):
        self.name=name
        self.n=n
        self.authors=authors
        self.publisher=publisher
        self.ISBN=ISBN
        self.year=year
    def display(self):
        print("book name : ",self.name)
        print("no of author : ",self.n)
        print("list of authors : ",self.authors)
        print("publisher : ",self.publisher)
        print("ISBN no : ",self.ISBN)
        print("year : ",self.year)
class Coursebook(book):
    def __init__(self,name,n,authors,publisher,ISBN,year,course):
        super().__init__(name,n,authors,publisher,ISBN,year)
        self.course=course
    def display(self):
        super().display()
        print("course name : ",self.course)

In [38]:
obj1=Coursebook("harry potter",1,["mihir"],"Aryan",2468,2020,"movie")
obj1.display()

book name :  harry potter
no of author :  1
list of authors :  ['mihir']
publisher :  Aryan
ISBN no :  2468
year :  2020
course name :  movie


In [1]:
class student:
    def __init__(self,rollno,name,age,totalnum):
        self.rollno=rollno
        self.name=name
        self.age=age
        self.totalnum=totalnum
    def display():
        print("students rollno : ",self.rollno)
        print("students name : ",self.name)
        print("students age :",self.age)
        print("total num : ",self.totalnum)
    def __equ__(self,other):
        if self.totalnum==other.totalnum:
            return True
        else:
            return False

In [2]:
s1=student(1,"aryan",20,85)
s2=student(2,"mihir",19,89)
if s1==s2:
    print(f"{s1.name} and {s2.name} have same marks!!")

In [ ]:
--------------------------------------------------------------------------------------------------------------------------------

In [3]:
class Bill:
    rates = {"HDD":5000, "RAM":2000, "Printer":6000, "Pendrive":800}
    items = {"HDD":0, "RAM":0, "Printer":0, "Pendrive":0}
    
    for i,j in rates.items():
        print(i,j)
        accept = input("Want this item? (Y/N)").upper()
        if accept == 'Y':
            items[i] = int(input("Enter No. of "+i+" 's: '"))*rates[i]
        print()
    
    def __init__(self):
        print("1. Cash Payment")
        print("2. Cheque Payment")
        payment_method = int(input("Enter Method 1/2:"))
        if payment_method == 1:
            cashpayment()
        else:
            chequepayment()

class cashpayment(Bill):
    def __init__(self):
        print()
        print("Payment Method is Cash")
        sum=0
        for i,j in self.items.items():
            sum += j
        print("Total Amount to Pay:",sum)
        d = {"2000 Rs Notes:":2000 , "500 Rs Notes:":500 , "100 Rs Notes:":100,
            "50 Rs Notes:":50,"20 Rs Notes:":20, "10 Rs Notes:":10}
        print()
        for i,j in d.items():
            if sum >= j:
                print(i + ":" ,sum//j)
                sum = sum%j

class chequepayment(Bill):
    def __init__(self):
        print()
        print("Payment Method is Cheque")
        sum=0
        for i,j in self.items.items():
            sum += j
        print("Total Amount to Pay:",sum)
        print()
        Chq_No = int(input("Enter Cheque Number:"))
        Bank = input("Enter Bank Name:")
        print()
        print("Cheque Details:")
        print("Cheque Number:",Chq_No)
        print("Bank Name:",Bank)
customer = Bill()    

HDD 5000
Want this item? (Y/N)n

RAM 2000
Want this item? (Y/N)n

Printer 6000
Want this item? (Y/N)n

Pendrive 800
Want this item? (Y/N)n

1. Cash Payment
2. Cheque Payment
Enter Method 1/2:1

Payment Method is Cash
Total Amount to Pay: 0



In [1]:
import numpy as np
import sys

s=range(1000)

print("size of each element pf list in bytes : ",sys.getsizeof(s))
print("size of whole list in bytes : ",sys.getsizeof(s)*len(s))

d=np.arange(1000)

print("size of each element of numpy array in bytes : ",d.itemsize)
print("size of whole numpy array in bytes : ",d.size*d.itemsize)

size of each element pf list in bytes :  48
size of whole list in bytes :  48000
size of each element of numpy array in bytes :  4
size of whole numpy array in bytes :  4000


In [4]:
import numpy as np
x=np.array(42)
print(x)
print(type(x))
print(x.ndim)

42
<class 'numpy.ndarray'>
0


In [3]:
import numpy as np
x=np.array([[1,2,3,4,5]])
print(x)
print(type(x))
print(x.ndim)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
2


In [8]:
import numpy as np
x=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,222,2]]])
print(x)
print(type(x))
print(x.ndim)
print(x[1,1,1])

[[[  1   2   3]
  [  1   2   3]]

 [[  1   2   3]
  [  1 222   2]]]
<class 'numpy.ndarray'>
3
222


In [7]:
print(x[1,1,2]+x[0,1,1])

4


In [ ]:
import numpy as np
x=np.array([1,2,3,4],[5,6,7],)
print(x)
print(type(x))
print(x.ndim)
print(x[1,1,1])

In [ ]:
--------------------------------------------------------------------------------------------------------------------------------

In [2]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [9]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [19]:
import numpy as np
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,4)
print(newarr)

[array([1]), array([2]), array([3]), array([4])]


In [20]:
import numpy as np
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,3)
print(newarr)

[array([1, 2]), array([3]), array([4])]


In [17]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr1,4)
print(newarr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [22]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr1,3,axis=1)
print(newarr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32)]


In [24]:
import numpy as np
arr1=np.array([1,2,3,4,5,4,6,4,3])
newarr=np.where(arr1==4)
print(newarr)

(array([3, 5, 7], dtype=int64),)


In [25]:
import numpy as np
arr1=np.array([[1,2],[3,4],[4,5],[6,4]])
newarr=np.where(arr1==4)
print(newarr)
#[3,4]=[1,1]
#[4,5]=[2,0]
#[6,4]=[3,1]

(array([1, 2, 3], dtype=int64), array([1, 0, 1], dtype=int64))


In [30]:
import numpy as np
arr1=np.array([[[1,2,3],[3,4,5]],[[5,4,6],[2,4,5]]])
newarr=np.where(arr1==4)
print(newarr)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64), array([1, 1, 1], dtype=int64))


In [35]:
import numpy as np
arr1=np.array([1,2,4,3,6,5,2])
print(np.sort(arr1))
arr2=np.array(['banana','apple','cherry','strobary','dragon fruit'])
print(np.sort(arr2))
arr3=np.array([True,False,True])
print(np.sort(arr3))

[1 2 2 3 4 5 6]
['apple' 'banana' 'cherry' 'dragon fruit' 'strobary']
[False  True  True]


In [39]:
import numpy as np
arr1=np.array([1,2,4,3,6,5,2])
print(np.sort(arr1,axis=-1))

[1 2 2 3 4 5 6]


In [40]:
import numpy as np
arr1=np.array([1,2,4,3,6,5,2])
print(np.sort(arr1,axis=1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [41]:
import numpy as np
arr1=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr1))

[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [44]:
import numpy as np
arr1=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr1,axis=1))

[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [52]:
import numpy as np
arr1=np.array([[3,4,2],
               [1,7,3],
               [4,2,5]])
print(np.sort(arr1,axis=0))

[[1 2 2]
 [3 4 3]
 [4 7 5]]


In [46]:
import numpy as np
arr1=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr1,axis=None))

[1 2 2 3 3 4 4 5 7]


In [47]:
import numpy as np
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr1))

[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]


In [49]:
import numpy as np
arr1=np.array([[[3,2,8],
                [7,9,3]],
               [[6,7,2],
                [9,6,4]]])
print(np.sort(arr1,axis=1))

[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]


In [50]:
import numpy as np
arr1=np.array([[[3,2,8],[7,9,3]],
               [[6,7,2],[9,6,4]]])
print(np.sort(arr1,axis=0))

[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]


In [95]:
from numpy import random
x=random.randint(1,100)
print(x)

15


In [105]:
from numpy import random
x=random.randint(1,100,size=(5))
print(x)

[96 46 71 39 44]


In [106]:
from numpy import random
x=random.randint(1,100,size=(3,5))
print(x)

[[20 58 29 28 97]
 [50 74 15 10 49]
 [ 2 30 55 28 75]]


In [108]:
from numpy import random
x=random.randint(1,100,size=(2,2,3))
print(x)

[[[48 79 14]
  [39 90 52]]

 [[67 49 81]
  [56 48 93]]]


In [109]:
from numpy import random
x=random.rand()
print(x)
#output=[0,1)

0.3947779673307603


In [110]:
from numpy import random
x=random.rand(3,5)
print(x)
#output=[0,1)

[[0.68441942 0.67856947 0.60553869 0.67069323 0.86062709]
 [0.01768622 0.80344783 0.85866    0.81090099 0.36778352]
 [0.82794214 0.96351315 0.75090485 0.07478725 0.04877743]]


In [140]:
from numpy import random
x=random.choice([1,3,5,7,9],size=(3,5))
print(x)
#output=[0,1)

[[5 1 3 1 1]
 [1 3 9 5 3]
 [3 1 3 3 5]]


In [6]:
from numpy import random
attemp=7
check=random.randint(1,101)
for i in range(7):
    user=input("Enter a number = ")
    if user==check:
        print("🥇your number is correct🥇",user)
        break
    else:
        print("🤡your number is incorrect🤡")
        attemp-=1
        print("your attemp is = ",attemp)
print("game over")
if attemp==0:
    print("your correct number is = ",check)

Enter a number = 18
🤡your number is incorrect🤡
your attemp is =  6
Enter a number = 45
🤡your number is incorrect🤡
your attemp is =  5
Enter a number = 666
🤡your number is incorrect🤡
your attemp is =  4
Enter a number = 44
🤡your number is incorrect🤡
your attemp is =  3
Enter a number = 3
🤡your number is incorrect🤡
your attemp is =  2
Enter a number = 237
🤡your number is incorrect🤡
your attemp is =  1
Enter a number = 90
🤡your number is incorrect🤡
your attemp is =  0
game over
your correct number is =  24
